/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.EventoControll;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;
import vo.EventoVO;

/**
 *
 * @author cesarvergara
 */
public class HomeEventoView extends javax.swing.JFrame {

    /**
     * Creates new form Aplicacao
     */
    public HomeEventoView() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.buscarEventos();
        this.inputBuscarEvento.setBorder(new LineBorder(Color.WHITE, 5, false));
    }

    public void buscarEventos() {
        try {

            EventoControll eventoControl = new EventoControll();
            ArrayList<EventoVO> eventos = eventoControl.buscar();
            this.popularTabelaEvento(eventos);

        } catch (Exception ex) {

            Logger.getLogger(HomeEventoView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    public void popularTabelaEvento(ArrayList<EventoVO> eventos) {

        try {

            DefaultTableModel table = (DefaultTableModel) eventsTable.getModel();
            table.fireTableDataChanged();
            table.setRowCount(0);

            for (EventoVO eventoVO : eventos) {

                table.addRow(new Object[]{eventoVO.getNome(), eventoVO.getData(), eventoVO.getHoraInicial(), eventoVO.getHoraFinal(), eventoVO.getTipoEvento()});
            }

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher a tabela.", "Buscar Eventos", JOptionPane.ERROR_MESSAGE);
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        eventsTable = new javax.swing.JTable();
        textEvento = new javax.swing.JLabel();
        novoEvento = new javax.swing.JLabel();
        editEvent = new javax.swing.JLabel();
        deleteEvent = new javax.swing.JLabel();
        voltar = new javax.swing.JLabel();
        inputBuscarEvento = new javax.swing.JTextField();
        textBuscarEvento = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(44, 62, 80));

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));

        eventsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome do Evento", "Data", "Hora inicial", "Hora final", "Tipo de evento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(eventsTable);

        textEvento.setFont(new java.awt.Font("Open Sans", 1, 13)); // NOI18N
        textEvento.setForeground(new java.awt.Color(255, 255, 255));
        textEvento.setText("Eventos");

        novoEvento.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        novoEvento.setForeground(new java.awt.Color(3, 218, 198));
        novoEvento.setText("+ NOVO EVENTO");
        novoEvento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                novoEventoMouseClicked(evt);
            }
        });

        editEvent.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        editEvent.setForeground(new java.awt.Color(3, 218, 198));
        editEvent.setText("EDITAR");
        editEvent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editEventMouseClicked(evt);
            }
        });

        deleteEvent.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        deleteEvent.setForeground(new java.awt.Color(244, 67, 54));
        deleteEvent.setText("EXCLUIR");
        deleteEvent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteEventMouseClicked(evt);
            }
        });

        voltar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        voltar.setForeground(new java.awt.Color(244, 67, 54));
        voltar.setText("VOLTAR");
        voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                voltarMouseClicked(evt);
            }
        });

        inputBuscarEvento.setBorder(null);
        inputBuscarEvento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputBuscarEventoKeyReleased(evt);
            }
        });

        textBuscarEvento.setFont(new java.awt.Font("Open Sans", 1, 13)); // NOI18N
        textBuscarEvento.setForeground(new java.awt.Color(255, 255, 255));
        textBuscarEvento.setText("Buscar Evento:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textEvento)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(4, 4, 4)
                                    .addComponent(voltar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(deleteEvent)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(editEvent)
                                    .addGap(18, 18, 18)
                                    .addComponent(novoEvento))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(textBuscarEvento)
                        .addGap(30, 30, 30)
                        .addComponent(inputBuscarEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textEvento)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputBuscarEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBuscarEvento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(novoEvento)
                    .addComponent(editEvent)
                    .addComponent(deleteEvent)
                    .addComponent(voltar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void novoEventoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_novoEventoMouseClicked
        FormularioEventoView form = new FormularioEventoView();
        form.setVisible(true);
        dispose();
    }//GEN-LAST:event_novoEventoMouseClicked

    private void voltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarMouseClicked
        HomeProgramaView telaInicial = new HomeProgramaView();
        telaInicial.setVisible(true);
        dispose();
    }//GEN-LAST:event_voltarMouseClicked

    private void inputBuscarEventoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputBuscarEventoKeyReleased
        try {
        
            String nome = this.inputBuscarEvento.getText();
            
            EventoControll eventoControl = new EventoControll();
            ArrayList<EventoVO> eventos = eventoControl.buscarNome(nome);
            
            this.popularTabelaEvento(eventos);
       
        } catch (SQLException ex) {
        
            Logger.getLogger(HomeEventoView.class.getName()).log(Level.SEVERE, null, ex);
       
        } catch (Exception ex) {
            
            Logger.getLogger(HomeEventoView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_inputBuscarEventoKeyReleased

    private void deleteEventMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteEventMouseClicked

        try {

            EventoVO eventoVO = new EventoVO();
            eventoVO.setNome(this.eventsTable.getValueAt(this.eventsTable.getSelectedRow(), 0).toString());
            
            int op = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir permanentemente o evento " + eventoVO.getNome() + "?", "Exclusão de Evento", JOptionPane.YES_NO_CANCEL_OPTION);

            if (op == 0) {

                EventoControll eventoControl = new EventoControll(eventoVO);
                eventoControl.excluir();

                JOptionPane.showMessageDialog(rootPane, "Evento excluído com sucesso!", "Exclusão de Evento", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (ArrayIndexOutOfBoundsException ex) {

            JOptionPane.showMessageDialog(rootPane, "Selecione um evento na tabela", "Exclusão de Evento", JOptionPane.WARNING_MESSAGE);

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(rootPane, "ERRO! Evento vinculado com alunos", "Exclusão de Evento", JOptionPane.ERROR_MESSAGE);

        } finally {
            
            this.buscarEventos();
        }


    }//GEN-LAST:event_deleteEventMouseClicked

    private void editEventMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editEventMouseClicked

            try {

            EventoVO eventoVO = new EventoVO();

            eventoVO.setNome((String) this.eventsTable.getValueAt(this.eventsTable.getSelectedRow(), 0));
            eventoVO.setData((String) this.eventsTable.getValueAt(this.eventsTable.getSelectedRow(), 1));
            eventoVO.setHoraInicial((String) this.eventsTable.getValueAt(this.eventsTable.getSelectedRow(), 2));
            eventoVO.setHoraFinal((String) this.eventsTable.getValueAt(this.eventsTable.getSelectedRow(), 3));
            eventoVO.setTipoEvento((String) this.eventsTable.getValueAt(this.eventsTable.getSelectedRow(), 4));
            
            FormularioEventoView form = new FormularioEventoView(this, eventoVO);
            form.setVisible(true);

        } catch (ArrayIndexOutOfBoundsException ex) {

            JOptionPane.showMessageDialog(rootPane, "Selecione um registro na tabela", "Edição de Registro", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_editEventMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeEventoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeEventoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeEventoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeEventoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeEventoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel deleteEvent;
    private javax.swing.JLabel editEvent;
    private javax.swing.JTable eventsTable;
    private javax.swing.JTextField inputBuscarEvento;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel novoEvento;
    private javax.swing.JLabel textBuscarEvento;
    private javax.swing.JLabel textEvento;
    private javax.swing.JLabel voltar;
    // End of variables declaration//GEN-END:variables
}
